import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { Tool, Blog, Category, FAQ } from '../types/index.js';

const STORAGE_KEY_URL = 'toolverse_supabase_url';
const STORAGE_KEY_ANON = 'toolverse_supabase_anon_key';

let cachedClient: SupabaseClient | null = null;
let currentConfig = {
  url: '',
  anonKey: ''
};

export function isValidSupabaseUrl(url: unknown): boolean {
  if (!url || typeof url !== 'string') return false;
  const trimmed = url.trim();
  if (!trimmed.startsWith('https://') && !trimmed.startsWith('http://')) return false;
  try {
    const parsed = new URL(trimmed);
    return (parsed.protocol === 'https:' || parsed.protocol === 'http:') && Boolean(parsed.hostname);
  } catch {
    return false;
  }
}

export function getSupabaseConfig(): { url: string; anonKey: string; isEnv: boolean } {
  const metaEnv = (import.meta as any).env || {};
  const envUrl = (metaEnv.VITE_SUPABASE_URL || '').trim();
  const envKey = (metaEnv.VITE_SUPABASE_ANON_KEY || '').trim();

  if (isValidSupabaseUrl(envUrl) && envKey) {
    return { url: envUrl, anonKey: envKey, isEnv: true };
  }

  try {
    const localUrl = (localStorage.getItem(STORAGE_KEY_URL) || '').trim();
    const localKey = (localStorage.getItem(STORAGE_KEY_ANON) || '').trim();
    if (isValidSupabaseUrl(localUrl) && localKey) {
      return { url: localUrl, anonKey: localKey, isEnv: false };
    }
  } catch {
    // Ignore localStorage errors
  }

  return { url: '', anonKey: '', isEnv: false };
}

export function saveSupabaseConfig(url: string, anonKey: string): void {
  const cleanUrl = url.trim();
  const cleanKey = anonKey.trim();

  if (isValidSupabaseUrl(cleanUrl) && cleanKey) {
    localStorage.setItem(STORAGE_KEY_URL, cleanUrl);
    localStorage.setItem(STORAGE_KEY_ANON, cleanKey);
  } else {
    localStorage.removeItem(STORAGE_KEY_URL);
    localStorage.removeItem(STORAGE_KEY_ANON);
  }
  cachedClient = null; // Invalidate client to recreate with new credentials
}

export function clearSupabaseConfig(): void {
  try {
    localStorage.removeItem(STORAGE_KEY_URL);
    localStorage.removeItem(STORAGE_KEY_ANON);
  } catch {
    // ignore
  }
  cachedClient = null;
}

export function getSupabaseClient(): SupabaseClient | null {
  const config = getSupabaseConfig();
  
  if (!isValidSupabaseUrl(config.url) || !config.anonKey) {
    return null;
  }

  // Check if we can reuse cached instance
  if (cachedClient && currentConfig.url === config.url && currentConfig.anonKey === config.anonKey) {
    return cachedClient;
  }

  try {
    currentConfig = { url: config.url, anonKey: config.anonKey };
    cachedClient = createClient(config.url, config.anonKey, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        storageKey: 'toolverse_supabase_auth_token'
      }
    });
    return cachedClient;
  } catch (err) {
    console.warn('Failed to initialize Supabase client:', err);
    return null;
  }
}

export async function testSupabaseConnection(url: string, anonKey: string): Promise<{ success: boolean; message: string }> {
  try {
    const cleanUrl = (url || '').trim();
    const cleanKey = (anonKey || '').trim();

    if (!cleanUrl || !cleanKey) {
      return { success: false, message: 'Please provide both Project URL and Anon API Key' };
    }

    if (!isValidSupabaseUrl(cleanUrl)) {
      return { success: false, message: 'Supabase URL must be a valid HTTP or HTTPS URL (e.g., https://your-project.supabase.co)' };
    }

    const testClient = createClient(cleanUrl, cleanKey, {
      auth: { persistSession: false }
    });

    // Test reachability and API key validity via session lookup
    const { error } = await testClient.auth.getSession();
    if (error && !error.message.includes('Auth session missing')) {
      return { success: false, message: error.message };
    }

    return { success: true, message: 'Connected to Supabase successfully!' };
  } catch (err: any) {
    return { success: false, message: err.message || 'Could not connect to Supabase endpoint.' };
  }
}

/**
 * SQL Schema migration script that users can paste into their Supabase SQL Editor
 */
export const SUPABASE_SQL_SCHEMA = `-- ========================================================
-- ToolVerse Complete Database Schema for Supabase
-- Paste and run this script in your Supabase SQL Editor:
-- Supabase Dashboard -> SQL Editor -> New Query -> Run
-- ========================================================

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    icon TEXT DEFAULT 'Folder',
    color TEXT DEFAULT '#B5824C',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Tools Table
CREATE TABLE IF NOT EXISTS public.tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    short_description TEXT,
    full_description TEXT,
    category TEXT REFERENCES public.categories(slug) ON UPDATE CASCADE ON DELETE SET NULL,
    keywords TEXT,
    faq JSONB DEFAULT '[]'::jsonb,
    icon TEXT DEFAULT 'Sparkles',
    featured INTEGER DEFAULT 0,
    trending INTEGER DEFAULT 0,
    usage_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Blogs Table
CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    excerpt TEXT,
    content TEXT,
    category TEXT,
    author TEXT DEFAULT 'ToolVerse Editorial Team',
    cover_image TEXT,
    read_time TEXT DEFAULT '5 min read',
    tags TEXT,
    is_published INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create FAQs Table
CREATE TABLE IF NOT EXISTS public.faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category TEXT,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create Contact Messages Table
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    is_read INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================================================
-- Row Level Security (RLS) Configuration
-- ========================================================

-- Enable RLS on all tables
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tools ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Public Read Policies (Allow anyone to view tools, categories, blogs, and faqs)
CREATE POLICY "Public Read Categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public Read Tools" ON public.tools FOR SELECT USING (true);
CREATE POLICY "Public Read Published Blogs" ON public.blogs FOR SELECT USING (true);
CREATE POLICY "Public Read FAQs" ON public.faqs FOR SELECT USING (true);

-- Public Insert for Inquiries
CREATE POLICY "Public Insert Contact" ON public.contact_messages FOR INSERT WITH CHECK (true);

-- Full Access for Authenticated Admin Users
CREATE POLICY "Admin Full Access Categories" ON public.categories FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin Full Access Tools" ON public.tools FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin Full Access Blogs" ON public.blogs FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin Full Access FAQs" ON public.faqs FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin Full Access Contact" ON public.contact_messages FOR ALL TO authenticated USING (true) WITH CHECK (true);
`;

/**
 * Pushes local database data (categories, tools, blogs, faqs) to Supabase tables
 */
export async function pushDataToSupabase(data: {
  categories: Category[];
  tools: Tool[];
  blogs: Blog[];
  faqs: FAQ[];
}): Promise<{ success: boolean; message: string; details?: any }> {
  const client = getSupabaseClient();
  if (!client) {
    return { success: false, message: 'Supabase client is not configured.' };
  }

  try {
    let syncedCats = 0;
    let syncedTools = 0;
    let syncedBlogs = 0;
    let syncedFaqs = 0;

    // 1. Categories
    if (data.categories.length > 0) {
      const catPayload = data.categories.map(c => ({
        name: c.name,
        slug: c.slug,
        description: c.description,
        icon: c.icon || 'Folder',
        color: c.color || '#B5824C'
      }));
      const { error: catError } = await client.from('categories').upsert(catPayload, { onConflict: 'slug' });
      if (catError) {
        throw new Error(`Categories sync error: ${catError.message}. Did you run the SQL schema script in Supabase?`);
      }
      syncedCats = data.categories.length;
    }

    // 2. Tools
    if (data.tools.length > 0) {
      const toolsPayload = data.tools.map(t => ({
        name: t.name,
        slug: t.slug,
        short_description: t.short_description,
        full_description: t.full_description,
        category: t.category,
        keywords: t.keywords,
        faq: typeof t.faq === 'string' ? JSON.parse(t.faq || '[]') : t.faq || [],
        icon: t.icon || 'Sparkles',
        featured: t.featured || 0,
        trending: t.trending || 0,
        usage_count: t.usage_count || 0
      }));
      const { error: toolsError } = await client.from('tools').upsert(toolsPayload, { onConflict: 'slug' });
      if (toolsError) {
        throw new Error(`Tools sync error: ${toolsError.message}`);
      }
      syncedTools = data.tools.length;
    }

    // 3. Blogs
    if (data.blogs.length > 0) {
      const blogsPayload = data.blogs.map(b => ({
        title: b.title,
        slug: b.slug,
        excerpt: b.excerpt,
        content: b.content,
        category: b.category,
        author: b.author || 'ToolVerse Editorial Team',
        cover_image: b.cover_image || b.featured_image,
        reading_time: b.reading_time || '5 min read',
        tags: b.tags,
        published: b.published ?? 1
      }));
      const { error: blogsError } = await client.from('blogs').upsert(blogsPayload, { onConflict: 'slug' });
      if (blogsError) {
        throw new Error(`Blogs sync error: ${blogsError.message}`);
      }
      syncedBlogs = data.blogs.length;
    }

    // 4. FAQs
    if (data.faqs.length > 0) {
      const faqsPayload = data.faqs.map(f => ({
        question: f.question,
        answer: f.answer,
        category: f.category
      }));
      const { error: faqsError } = await client.from('faqs').upsert(faqsPayload);
      if (faqsError) {
        throw new Error(`FAQs sync error: ${faqsError.message}`);
      }
      syncedFaqs = data.faqs.length;
    }

    return {
      success: true,
      message: `Successfully synced ${syncedCats} categories, ${syncedTools} tools, ${syncedBlogs} articles, and ${syncedFaqs} FAQs to your Supabase project!`,
      details: { syncedCats, syncedTools, syncedBlogs, syncedFaqs }
    };
  } catch (err: any) {
    return {
      success: false,
      message: err.message || 'Failed to sync data to Supabase.'
    };
  }
}

/**
 * Fetches all database entities from Supabase tables
 */
export async function fetchDataFromSupabase(): Promise<{
  categories: Category[];
  tools: Tool[];
  blogs: Blog[];
  faqs: FAQ[];
} | null> {
  const client = getSupabaseClient();
  if (!client) return null;

  try {
    const [catsRes, toolsRes, blogsRes, faqsRes] = await Promise.all([
      client.from('categories').select('*').order('id', { ascending: true }),
      client.from('tools').select('*').order('id', { ascending: true }),
      client.from('blogs').select('*').order('id', { ascending: false }),
      client.from('faqs').select('*').order('id', { ascending: true })
    ]);

    if (catsRes.error || toolsRes.error || blogsRes.error || faqsRes.error) {
      return null;
    }

    return {
      categories: (catsRes.data || []) as Category[],
      tools: (toolsRes.data || []).map(t => ({
        ...t,
        faq: typeof t.faq === 'object' ? JSON.stringify(t.faq) : t.faq
      })) as Tool[],
      blogs: (blogsRes.data || []) as Blog[],
      faqs: (faqsRes.data || []) as FAQ[]
    };
  } catch {
    return null;
  }
}
